apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configstore
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: configstore
    spec:
      containers:
        - name: configstore
          image: 410240865662.dkr.ecr.us-west-2.amazonaws.com/configstore:0.0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          volumeMounts:
            - mountPath: /var/configstore
              name: data
          resources:
            requests:
              memory: "768Mi"
            limits:
              memory: "768Mi"
      volumes:
        - name: data
          awsElasticBlockStore:
            volumeID: vol-05370cb1
            fsType: ext4
      nodeSelector:
        lunchbadger.com/node-type: worker
---
apiVersion: v1
kind: Service
metadata:
  name: configstore
  labels:
    run: configstore
spec:
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
  selector:
    run: configstore
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: configstore
spec:
  rules:
  - host: api.lunchbadger.com
    http:
      paths:
      - backend:
          serviceName: configstore
          servicePort: 80
