apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configstore
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: configstore
    spec:
      containers:
        - name: configstore
          image: localhost:31000/configstore:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/configstore
              name: data
      volumes:
        - name: data
          awsElasticBlockStore:
            volumeID: vol-6caf01d9
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: configstore
  labels:
    run: configstore
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    run: configstore
  type: ClusterIP
